### ISSUE TITLE
Add feature for ReturnKey.Next to move to another Entry

### ISSUE THREAD

**Issue by therealjohn** [brminnick/EntryCustomReturnPlugin#21]
The Next key is great, but it's really awesome if it causes the focus to move to another control. I'm wondering if we can add a feature to this so that when Next is pressed, another control get's Focus. 

Something like this:

```
var goReturnTypeCustomEntry = new CustomReturnEntry
{
    ReturnType = ReturnType.Go
};

var nextReturnTypeCustomEntry = new CustomReturnEntry
{
    ReturnType = ReturnType.Next,
    NextViewProperty = goReturnTypeCustomEntry
};
```

```
    public static readonly BindableProperty NextViewProperty = 
        BindableProperty.Create("NextView", typeof(View), typeof(CustomReturnEntry));
 
    public View NextView
    {
        get { return (View)GetValue(NextViewProperty); }
        set { SetValue(NextViewProperty, value); }
    }
 
    public void OnNext()
    {
        NextView?.Focus();
    }
```

Similar to [what this blog is explaining.](http://www.fabiocozzolino.eu/move-focus-next-control-xamarin-forms/) What are your thoughts?

**Comment by brminnick** [comment]
Hey @therealjohn!

Great idea! It can already be done using `ReturnCommand`.

My concern is that `NextView` would clutter the API and just add confusion as to when to use `ReturnCommand` vs. `NextView`.

```
var goReturnTypeCustomEntry = new CustomReturnEntry
{
    ReturnType = ReturnType.Go
};


var nextReturnTypeCustomEntry = new CustomReturnEntry
{
    ReturnType = ReturnType.Next,
    ReturnnCommand = new Command(() => goReturnTypeCustomEntry.Focus())
};
```

**Comment by therealjohn** [comment]
Oh! This is great! I suppose I should have taken that nap today...

I realized later I could also just do:

```
entry.Completed += (o,e) => otherEntry.Focus();
```

Thanks for the quick response. I'll close this.
