### ISSUE TITLE
Respect CanExecute on commands

### ISSUE THREAD

**Issue by RobGibbens** [brminnick/EntryCustomReturnPlugin#27]
When binding to commands, the return button should respect the `CanExecute` value of the command.  If possible, it should change the UI, but at a minimum it should not try to call `Execute` on the command

**Comment by brminnick** [comment]
Thanks Rob! You’re totally right - I’m not honoring CanExecute right now. I’ll add this to the next release. 👍

For changing the coloration of the button when the ReturnCommand is disabled, I’ll have to look into the iOS and Android APIs to see if that’s possible. Off the top of my head, I don’t think it is, but it’s a great idea and worth looking g into!

**Comment by brminnick** [comment]
Hey Rob! I've published v4.1.0-pre1 which now honors CanExecute.

I haven't had a chance to look into changing the color/behavior of the Return Key yet.

**Comment by brminnick** [comment]
Changing the Keyboard Return Key color isn't supported:

https://stackoverflow.com/a/5659885/5953643

https://stackoverflow.com/a/28949934/5953643
