### ISSUE TITLE
Extend Capability to Xamarin.Forms.Editor

### ISSUE THREAD

**Issue by brminnick** [brminnick/EntryCustomReturnPlugin#3]

**Comment by nielscup** [comment]
Don't you need the return key as it is in an Editor because it is a multi line text field (mostly)? I would like to see this functionality in a picker control however...

**Comment by brminnick** [comment]
@nielscup - agreed; implementing it for `Xamarin.Forms.Editor` would be confusing to users looking to use the Return key for a carriage return. Implementing it for the picker is a cool idea 👍
