### ISSUE TITLE
Can't click into field

### ISSUE THREAD

**Issue by Osmosis311** [brminnick/EntryCustomReturnPlugin#30]
One of my iOS users is reporting that they can't edit the text in the custom entry field.  They tap on it but no cursor appears and no keyboard pops up.

Any ideas?

Thanks!

**Comment by brminnick** [comment]
A few questions:

* Can you create a reproduction?
* What device is it happening on?
* What operating system is it happening on?
* What version of Xamarin.Forms are you building against?

**Comment by brminnick** [comment]
Closing issue - needs more data
