### ISSUE TITLE
ReturnButton type not showing up in iOS for keyboardType telephone

### ISSUE THREAD

**Issue by nielscup** [brminnick/EntryCustomReturnPlugin#31]
ReturnButton type not showing up in iOS for keyboardType telephone. Android does display the returnType button.

**Comment by zwilkin** [comment]
Same issue is occurring here.

I am implementing EntryCustomReturnPlugin through the Effect method in XAML file.

**Comment by brminnick** [comment]
@nielscup Can you elaborate more about the feature you're seeking?

The default iOS Numeric Keyboard doesn't have a return button.

<img width="511" alt="image" src="https://user-images.githubusercontent.com/13558917/54452898-67076780-4713-11e9-8fcb-fff61a37b8bc.png">

**Comment by brminnick** [comment]
@nielscup Can you elaborate further about the feature you're looking for?

The default `UIKeyboardType.phonePad` doesn't include a return button.

<img width="511" alt="image" src="https://user-images.githubusercontent.com/13558917/54453616-eba6b580-4714-11e9-8150-a258ad0bd77e.png">

**Comment by brminnick** [comment]
Closing pending follow up information
