### ISSUE TITLE
Rename command properties

### ISSUE THREAD

**Issue by jimbobbennett** [brminnick/EntryCustomReturnPlugin#6]
`SetReturnCommandProperty` and `GetReturnCommandProperty` on `ReturnTypeEffect` should be renamed to `SetReturnCommand` and `SetReturnCommand`.

Breaking change I know, so maybe add new methods and obsolete the existing ones.

**Comment by brminnick** [comment]
Thanks @jimbobbennett! I updated the API accordingly

https://github.com/brminnick/EntryCustomReturnPlugin/blob/master/Src/EntryCustomReturn.Forms.Plugin.Abstractions/Effects/ReturnTypeEffect.cs#L56
